# -*- coding: utf-8 -*-
"""BBQ資料庫

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P3uV-EixKFqwL_9Gx3_WuuDVCVTDz1rD
"""

import sqlite3

# 連接到資料庫（如果不存在就會建立新的）
conn = sqlite3.connect('BBQ.db')

# 創建一個用於與資料庫互動的游標物件
cursor = conn.cursor()

# 如果表格不存在，則創建一個名為 meat 的表格
cursor.execute('''
    CREATE TABLE IF NOT EXISTS meat(
        id INTEGER PRIMARY KEY,
        name TEXT,
        price INTEGER,
        quantity INTEGER
    )''')

# 增加三筆資料
cursor.execute("INSERT INTO meat(name, price, quantity) VALUES('chicken', 30, 5)")
cursor.execute("INSERT INTO meat(name, price, quantity) VALUES('beef', 55, 10)")
cursor.execute("INSERT INTO meat(name, price, quantity) VALUES('pork', 40, 15)")
conn.commit()

# 查詢並印出表格內容
cursor.execute("SELECT * FROM meat")
meat_records = cursor.fetchall()
print("\n初始表格內容:")
for record in meat_records:
    print(record)

# 將 pork 的價格改為 35; 將 chicken 的數量改為 30
cursor.execute("UPDATE meat SET price = 35 WHERE name = 'pork'")
cursor.execute("UPDATE meat SET quantity = 30 WHERE name = 'chicken'")
conn.commit()

# 查詢並印出表格內容
cursor.execute("SELECT * FROM meat")
meat_records = cursor.fetchall()
print("\n更新後的表格內容:")
for record in meat_records:
    print(record)

# 刪除價格為 40 的整筆資料
cursor.execute("DELETE FROM meat WHERE price = 40")
conn.commit()

# 查詢並印出表格內容
cursor.execute("SELECT * FROM meat")
meat_records = cursor.fetchall()
print("\n刪除後的表格內容:")
for record in meat_records:
    print(record)

# 關閉游標
cursor.close()

# 關閉與資料庫的連接
conn.close()

